-- CREATE TABLE & INDEX
-- Q12

-- Option 1)
CREATE TABLE EMP (
  EMP_NO      VARCHAR2(10) PRIMARY KEY,
  EMP_NM      VARCHAR2(30) NOT NULL,
  DEPT_CDODE  VARCHAR2(4) DEFAULT '0000' NOT NULL,
  JOIN_DATE   DATE NOT NULL,
  REGIST_DATE DATE NULL
);
CREATE INDEX IDX_EMP_01 ON EMP (JOIN_DATE);


-- Option 2)
CREATE TABLE EMP (
  EMP_NO      VARCHAR2(10) NOT NULL,
  EMP_NM      VARCHAR2(30) NOT NULL,
  DEPT_CDODE  VARCHAR2(4) DEFAULT '0000' NOT NULL,
  JOIN_DATE   DATE NOT NULL,
  REGIST_DATE DATE NULL
);
ALTER TABLE EMP ADD CONSTRAINT EMP_PK PRIMARY KEY (EMP_NO);
CREATE INDEX IDX_EMP_01 ON EMP (JOIN_DATE);

